export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "https://cdn.pixabay.com/photo/2018/02/27/06/30/skyscrapers-3184798_1280.jpg",
		user: {
			username: "johndoe",
			profileImg: "https://cdn.pixabay.com/photo/2020/05/09/13/29/photographer-5149664_1280.jpg",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "https://cdn.pixabay.com/photo/2016/02/11/16/59/dog-1194083_960_720.jpg",
					fullName: "Jane Doe",
				},
			},
			{
				_id: "2",
				text: "Its me again",
				user: {
					username: "jackiedoe",
					profileImg: "https://cdn.pixabay.com/photo/2016/02/11/16/59/dog-1194083_960_720.jpg",
					fullName: "Jackie Doe",
				},
			},
			{
				_id: "3",
				text: "Cool post",
				user: {
					username: "janedoe",
					profileImg: "https://cdn.pixabay.com/photo/2016/02/11/16/59/dog-1194083_960_720.jpg",
					fullName: "Jane Doe",
				},
			},
			{
				_id: "4",
				text: "All for it",
				user: {
					username: "janedoe",
					profileImg: "https://cdn.pixabay.com/photo/2016/02/11/16/59/dog-1194083_960_720.jpg",
					fullName: "Jane Doe",
				},
			},
			{
				_id: "5",
				text: "All for it",
				user: {
					username: "janedoe",
					profileImg: "https://cdn.pixabay.com/photo/2016/02/11/16/59/dog-1194083_960_720.jpg",
					fullName: "Jane Doe",
				},
			},
			{
				_id: "6",
				text: "All for it",
				user: {
					username: "janedoe",
					profileImg: "https://cdn.pixabay.com/photo/2016/02/11/16/59/dog-1194083_960_720.jpg",
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "johndoe",
			profileImg: "https://cdn.pixabay.com/photo/2016/02/11/16/59/dog-1194083_1280.jpg",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "https://cdn.pixabay.com/photo/2019/12/04/09/30/man-4672229_1280.jpg",
					fullName: "Jane Doe",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "https://cdn.pixabay.com/photo/2016/03/27/19/03/crowd-1283691_1280.jpg",
		user: {
			username: "johndoe",
			profileImg: "https://cdn.pixabay.com/photo/2019/08/29/12/10/model-4438821_1280.jpg",
			fullName: "John Doe",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "https://cdn.pixabay.com/photo/2020/05/09/13/29/photographer-5149664_1280.jpg",
		user: {
			username: "johndoe",
			profileImg: "https://cdn.pixabay.com/photo/2020/10/28/14/01/man-5693573_960_720.jpg",
			fullName: "John Doe",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "janedoe",
					profileImg: "",
					fullName: "Jane Doe",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "John Doe",
		username: "johndoe",
		profileImg: "https://cdn.pixabay.com/photo/2019/08/29/12/10/model-4438821_1280.jpg",
	},
	{
		_id: "2",
		fullName: "Jane Doe",
		username: "janedoe",
		profileImg: "https://cdn.pixabay.com/photo/2020/10/28/14/01/man-5693573_960_720.jpg",
	},
	{
		_id: "3",
		fullName: "Bob Doe",
		username: "bobdoe",
		profileImg: "https://cdn.pixabay.com/photo/2016/02/11/16/59/dog-1194083_1280.jpg",
	},
	{
		_id: "4",
		fullName: "Daisy Doe",
		username: "daisydoe",
		profileImg: "https://cdn.pixabay.com/photo/2019/08/29/12/10/model-4438821_1280.jpg",
	},
];

  // // Generate responsive Cloudinary URL
	// const image = POSTS[3]?.img;
	// const responsiveImageUrl = cloudinary.url(img, {
	// 	crop: 'limit', // Limits the size to the original dimensions
	// 	width: 'auto', // Automatically adjusts width
	// });

	// POSTS[3].img = responsiveImageUrl;